[tox]
envlist = py{310,311,312}-qiskit{1.0,1.4,2.0,2.3}

[testenv]
deps =
    pytest
    pytest-cov
    qiskit1.0: qiskit~=1.0.0
    qiskit1.4: qiskit~=1.4.5
    qiskit2.0: qiskit~=2.0.3
    qiskit2.3: qiskit~=2.3.0
commands =
    pytest tests/ --cov=QCut --cov-report=term-missing