[tox]
envlist = py{311,312}-qiskit{1.2,1.4,2.0,2.3}

[testenv]
recreate = True
deps =
    pytest
    pytest-cov
    qiskit1.2: qiskit~=1.2.0
    qiskit1.4: qiskit~=1.4.0
    qiskit2.0: qiskit~=2.0.3
    qiskit2.3: qiskit~=2.3.0
    qiskit1.2,qiskit1.4,qiskit2.0: iqm-client[qiskit]==33.0.4 
commands =
    pytest tests/ --cov=QCut --cov-report=term-missing

[testenv:type]
deps = ty
commands = uvx ty check QCut/