"""
A module for generating the QPD operations and inserting them into the circuit at
the appropriate locations.
"""

from __future__ import annotations

from itertools import product
from typing import Iterable

from qiskit.circuit import (
    CircuitInstruction,
    Qubit,
)

from QCut.cutlocation import CutLocation, SingleQubitCutLocation
from QCut.qpd import cz_qpd, identity_qpd, iswap_qpd, swap_qpd
from QCut.qpd_generate import qpd_from_gate

# Maps gate_name (from CutLocation.gate_name) to its hand-derived QPD list. Gates listed
# here use the table verbatim, everything else is generated by QCut.qpd_generate. New
# entries are only worth adding where the generated table is worse, as it can be for a
# gate whose Weyl frame needs extra local `u` gates that a hand derivation avoids.
QPD_REGISTRY: dict[str, list] = {
    "cz": cz_qpd,
    "swap": swap_qpd,
    "iswap": iswap_qpd,
}


def qpd_for_location(cut: CutLocation | SingleQubitCutLocation) -> list[dict]:
    """Return the QPD to use for one cut location.

    Wire cuts use the identity channel decomposition. Gate cuts prefer the hand-derived
    table in ``QPD_REGISTRY`` and otherwise generate one from the gate's matrix. The
    result is cached on the cut location, which is needed both to size the experiment
    tensor and to expand it.

    Raises:
        NotImplementedError: a gate cut with neither a table nor a usable gate.
        TypeError: an unrecognised cut location type.
    """
    if isinstance(cut, SingleQubitCutLocation):
        return identity_qpd
    if not isinstance(cut, CutLocation):
        raise TypeError(f"Unknown cut type: {type(cut)}")
    if cut._qpd is not None:
        return cut._qpd

    if cut.gate_name in QPD_REGISTRY:
        qpd = QPD_REGISTRY[cut.gate_name]
    elif cut.gate is not None:
        qpd = qpd_from_gate(cut.gate)
    else:
        raise NotImplementedError(
            f"No QPD available for gate '{cut.gate_name}'. Cut it with "
            "cutGate(<gate>, control, target) so the gate travels with the cut and a "
            "decomposition can be generated from it."
        )
    cut._qpd = qpd
    return qpd


def _insert_wire_cut_qpd(
    ind,
    op,
    subcircuit,
    offset,
    qpd_qubits,
    qpd,
    classical_bit_index,
    inserted_operations,
):
    if "Meas" in op.operation.name:  # if measure channel remove placeholder
        # and insert current
        # qpd operation
        qubit_index = subcircuit.find_bit(op.qubits[0]).index
        subcircuit.data.pop(ind + offset)  # remove plaxceholder
        # measure channel
        qpd_qubits.append(qubit_index)  # store index
        qubits_for_operation = [Qubit(subcircuit.qregs[0], qubit_index)]
        meas_op = qpd[int(op.operation.name.split("_")[-1])]["op_0"]
        if meas_op.name == "id-meas":  # if identity measure channel
            # store indices
            # remove extra classical bits and registers
            # _adjust_cregs(subcircuit)
            for subop in reversed(meas_op.data):
                subcircuit.data.insert(
                    ind + offset,
                    CircuitInstruction(
                        operation=subop.operation, qubits=qubits_for_operation
                    ),
                )
        else:
            for subop in reversed(meas_op.data):
                if subop.operation.name == "measure":
                    subcircuit.data.insert(
                        ind + offset,
                        CircuitInstruction(
                            operation=subop.operation,
                            qubits=qubits_for_operation,
                            clbits=[subcircuit.cregs[0][classical_bit_index]],
                        ),
                    )
                else:
                    subcircuit.data.insert(
                        ind + offset,
                        CircuitInstruction(
                            operation=subop.operation,
                            qubits=qubits_for_operation,
                        ),
                    )

            # increment classical bit counter
            classical_bit_index += 1

        inserted_operations += 1
        offset += len(meas_op.data) - 1

    if "Init" in op.operation.name:
        subcircuit.data.pop(ind + offset)
        init_op = qpd[int(op.operation.name.split("_")[-1])]["op_1"]
        qubits_for_operation = [
            Qubit(subcircuit.qregs[0], subcircuit.find_bit(x).index) for x in op.qubits
        ]
        for subop in reversed(init_op.data):
            subcircuit.data.insert(
                ind + offset,
                CircuitInstruction(
                    operation=subop.operation, qubits=qubits_for_operation
                ),
            )

        inserted_operations += 1
        offset += len(init_op) - 1

    return offset, classical_bit_index, inserted_operations


def _insert_2qubit_gate_cut_qpd(  # noqa: C901
    ind,
    op,
    subcircuit,
    offset,
    qpd_qubits,
    qpd,
    classical_bit_index,
    inserted_operations,
):
    if "_c_" in op.operation.name:  # if measure channel remove placeholder
        # and insert current
        # qpd operation

        qubit_index = subcircuit.find_bit(op.qubits[0]).index
        subcircuit.data.pop(ind + offset)  # remove plaxceholder
        # measure channel
        # qpd_qubits.append(qubit_index)  # store index
        qubits_for_operation = [Qubit(subcircuit.qregs[0], qubit_index)]
        meas_op = qpd[int(op.operation.name.split("_")[-1])]["op_0"]
        if meas_op.name in ["id-meas", "s", "sdg", "z"]:
            # if identity measure channel
            # store indices
            # remove extra classical bits and registers
            # if meas_op.name != "id-meas":
            #    _adjust_cregs(subcircuit)
            for subop in reversed(meas_op.data):
                subcircuit.data.insert(
                    ind + offset,
                    CircuitInstruction(
                        operation=subop.operation, qubits=qubits_for_operation
                    ),
                )
        else:
            for i, subop in enumerate(reversed(meas_op.data)):
                if subop.operation.name in ["measure"]:
                    subcircuit.data.insert(
                        ind + offset,
                        CircuitInstruction(
                            operation=subop.operation,
                            qubits=qubits_for_operation,
                            clbits=[subcircuit.cregs[0][classical_bit_index]],
                        ),
                    )
                else:
                    subcircuit.data.insert(
                        ind + offset,
                        CircuitInstruction(
                            operation=subop.operation,
                            qubits=qubits_for_operation,
                        ),
                    )

            # increment classical bit counter
            classical_bit_index += 1

        inserted_operations += 1
        offset += len(meas_op) - 1

    if "_t_" in op.operation.name:
        # and insert current
        # qpd operation
        qubit_index = subcircuit.find_bit(op.qubits[0]).index
        subcircuit.data.pop(ind + offset)  # remove plaxceholder
        # measure channel
        # qpd_qubits.append(qubit_index)  # store index
        qubits_for_operation = [Qubit(subcircuit.qregs[0], qubit_index)]
        meas_op = qpd[int(op.operation.name.split("_")[-1])]["op_1"]
        if meas_op.name in ["id-meas", "s", "sdg", "z"]:
            # if identity measure channel
            # store indices

            # remove extra classical bits and registers
            # if meas_op.name != "id-meas":
            #    _adjust_cregs(subcircuit)
            for subop in reversed(meas_op.data):
                subcircuit.data.insert(
                    ind + offset,
                    CircuitInstruction(
                        operation=subop.operation, qubits=qubits_for_operation
                    ),
                )
        else:
            for i, subop in enumerate(reversed(meas_op.data)):
                if subop.operation.name in ["measure"]:
                    subcircuit.data.insert(
                        ind + offset,
                        CircuitInstruction(
                            operation=subop.operation,
                            qubits=qubits_for_operation,
                            clbits=[subcircuit.cregs[0][classical_bit_index]],
                        ),
                    )
                else:
                    subcircuit.data.insert(
                        ind + offset,
                        CircuitInstruction(
                            operation=subop.operation,
                            qubits=qubits_for_operation,
                        ),
                    )

            # increment classical bit counter
            classical_bit_index += 1

        inserted_operations += 1
        offset += len(meas_op) - 1

    return offset, classical_bit_index, inserted_operations


def get_qpd_combinations(
    cut_locations: list[CutLocation | SingleQubitCutLocation],
) -> Iterable[tuple[dict, ...]]:
    """Get all possible combinations of the QPD operations so that each combination
    has len(cut_locations) elements.

    Args:
        cut_locations (list[CutLocation | SingleQubitCutLocation]): cut locations

    Returns:
        Iterable[tuple[dict, ...]]:
            Iterable of the possible QPD operations

    """
    qpd_lists = [qpd_for_location(cut) for cut in cut_locations]

    # Cartesian product across all qpd options per cut
    all_combinations = product(*qpd_lists)
    return all_combinations
